---
apiVersion: batch/v1
kind: Job
metadata:
  name: copyartifacts
spec:
  backoffLimit: 1
  template:
    metadata:
      name: copyartifacts
    spec:
      restartPolicy: "Never"
      volumes:
      - name: testvolume
        persistentVolumeClaim:
          claimName: pvc
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: copyartifacts
        image: alpine:3.7
        imagePullPolicy: Always
        command: ["sh", "-c", "rm -rf /public/*; while [ ! -d /public/artifacts ]; do echo Waiting for artifacts to be copied; sleep 2; done; sleep 10; "]
        volumeMounts:
        - mountPath: /public
          name: testvolume
