---
apiVersion: batch/v1
kind: Job
metadata:
  name: createchannel
spec:
  backoffLimit: 1
  template:
    metadata:
      name: createchannel
    spec:
      restartPolicy: "Never"
      volumes:
      - name: testvolume
        persistentVolumeClaim:
          claimName: pvc
      containers:
      - name: createchanneltx
        image: hyperledger/fabric-tools:x86_64-1.1.0
        imagePullPolicy: Always
        command: ["sh", "-c", "cd /public && pwd && ls && export FABRIC_CFG_PATH=$PWD; sleep 10;
        configtxgen -profile FourOrgsChannel -outputCreateChannelTx ${CHANNEL_NAME}.tx -channelID ${CHANNEL_NAME} && touch /public/status_channeltx_complete "]
        env:
        - name: CHANNEL_NAME
          value: channel1
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /public
          name: testvolume
          
      - name: createchannel
        image: hyperledger/fabric-peer:x86_64-1.1.0
        imagePullPolicy: Always
        command: ["sh", "-c", "while [ ! -f /public/status_channeltx_complete ]; do echo Waiting for channeltx; sleep 2; done;
        peer channel create -o ${ORDERER_URL} -c ${CHANNEL_NAME} -f /public/${CHANNEL_NAME}.tx && rm /public/status_channeltx_complete && touch /public/status_channelcreate_complete"]
        env:
        - name: CHANNEL_NAME
          value: channel1
        - name: ORDERER_URL
          value: blockchain-orderer:31010
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "false"
        - name: CORE_PEER_NETWORKID
          value: nid1
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /public/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/
        - name: CORE_LOGGING_LEVEL
          value: debug
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /public
          name: testvolume
